# docker-compose.yml
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: mini-sistema-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:pedidosdb
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_H2_CONSOLE_ENABLED=true
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: mini-sistema-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend  # Remove a condição de saúde
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge